### ISSUE TITLE
Add simple Python Programs

### ISSUE THREAD

**Issue by Akshu-on-github** [AkshayaKulasekaran/Basic-Programs-Python#1]
- Each python program must be in a separate file
- Keep it at a beginner's level
- Please add in documentation as and when necessary

**Comment by 0vj** [comment]
Please tell me what to add :)
with example :)
i can add Caesar encoder and decoder. its good ?

**Comment by Akshu-on-github** [comment]
@mr-tafreshi, yup, sounds good! The simple calculator code can be taken as an example

**Comment by prathimacode-hub** [comment]
Can I contribute to this repository? I can add URL Shortener or Music Player. @Akshu-on-github

**Comment by Akshu-on-github** [comment]
@prathimacode-hub, go ahead! 😄

**Comment by prathimacode-hub** [comment]
Thank you for providing me with this opportunity to collaborate.

**Comment by tausiq2003** [comment]
what I will do on this?

**Comment by Akshu-on-github** [comment]
Hey there, @tausiq2003 - you can make an (original, non-plagiarized) addition to the collection of beginner level python scripts!

This repo is something that I use for workshops and the like where I encourage newcomers to make their first contributions, so have at it 😁

**Comment by tausiq2003** [comment]
Yeah can I add new password generated code

**Comment by Akshu-on-github** [comment]
Sure thing!

**Comment by tausiq2003** [comment]
Thanks

**Comment by tausiq2003** [comment]
ok i am now add passwordgenerator code

**Comment by tausiq2003** [comment]
Ok now I am adding password generated code please merge it
