### ISSUE TITLE
[Doc] Fix Screenshots

### ISSUE THREAD

**Issue by Akshu-on-github** [AkshayaKulasekaran/Basic-Programs-Python#23]
## Problem Description

Screenshots look messy, require refining. Steps to follow:
- [x] Modify screenshots (base screenshots provided below)
- [x] Replace the following code:
  ```
  ![image](https://user-images.githubusercontent.com/61582763/106519739-c508e800-6501-11eb-9133-1de5952cfe40.png)
  ![image](https://user-images.githubusercontent.com/61582763/106519960-16b17280-6502-11eb-94eb-81fd3fabfd9e.png)
  ```
  with the new image code. (template below:)

    ```
  <img src="new-url" alt="alt-text" width=50%>
  <img src="new-url" alt="alt-text" width=50%>
  ```
- [x] Add `alt` and `width` attributes as per your discretion

## Base Images
<details>
<summary><b>Note:</b></summary>
<ol>
<li>These are the preferred base images, please feel free to take new ones.</li>
<li>Kindly double check if they are legible</li>
<li>You can refer to the original at <a href="https://github.com/Akshu-on-github/Basic-Programs-Python/blob/master/CONTRIBUTING.md/#adding-sample-code">
<ol>
</details>

<img src="https://user-images.githubusercontent.com/61582763/119229306-00710600-bb35-11eb-9018-20072d4113be.png" width=50%> <img src="https://user-images.githubusercontent.com/61582763/119229351-37dfb280-bb35-11eb-9a31-1aab0068bc7e.png" width=40%>
<img src="https://user-images.githubusercontent.com/61582763/119229466-d66c1380-bb35-11eb-921f-7977f6d770a3.png" width=100%>

**Comment by kritigupta45** [comment]
May I take up this issue?

**Comment by Akshu-on-github** [comment]
Sure thing @imkritigupta!
