### ISSUE TITLE
[ORG] Re-organise, Rename Programs

### ISSUE THREAD

**Issue by Akshu-on-github** [AkshayaKulasekaran/Basic-Programs-Python#30]
## Description
The project looks rather messy as there is no naming conversion enforced. It is also difficult to locate important files such as CoC, CONTRIBUTING.md, etc. in the long list of files. Thus, there's the requirement to re-organise and rename the program files

## Proposed Solution:
To combat this, I'd propose:
- [x] #36
- [x] #33
- [x] #32
- [x] [DOC] Add "Naming Convention" requirement in `./.github/ISSUE_TEMPLATE/sample-code.md`
- [x] #31
- [x] #40

**Comment by Akshu-on-github** [comment]
If anyone is interested, leave a comment - I'll open an issue for the same and you can take it up

**Comment by safalkora** [comment]
Interested!

**Comment by Akshu-on-github** [comment]
Hey @safalkora! Which task would you like to work on?

**Comment by safalkora** [comment]
I would like to work on  improve Contributing.md

**Comment by Akshu-on-github** [comment]
@safalkora, please confirm your interest by commenting on #31 and I'll assign it to you!

**Comment by GopinathBalaji** [comment]
Hey! I would like to work on Updating the list in Programs/README.md

**Comment by Akshu-on-github** [comment]
@GopinathBalaji, please confirm your interest by commenting on #32 so I can assign it to you 😃

**Comment by Akshu-on-github** [comment]
I've assigned the issue to you, @GopinathBalaji 👍

**Comment by tanvi355** [comment]
Hey! I would like to work on moving the program files to the `Programs` folder.

**Comment by Akshu-on-github** [comment]
I've assigned you to your respective issues @safalkora and @tanvi355 - thank you both for contributing!

**Comment by t-bello7** [comment]
Hello! I would like to rename the program files to fit Naming Convention.

**Comment by msaini26** [comment]
Hi @Akshu-on-github, if possible, I would also like to help update the list in Programs/README.md. I also commented on #32 😃

**Comment by Akshu-on-github** [comment]
@t-bello7 please confirm your interest in #36 - I'll assign it to you then

**Comment by Akshu-on-github** [comment]
@msaini26 - please check out the Issue in question for my response. Meanwhile, you can choose another issue to take up here

**Comment by t-bello7** [comment]
> @t-bello7 please confirm your interest in #36 - I'll assign it to you then

Yes, I'm interested. 🦾

**Comment by Akshu-on-github** [comment]
You need to be a part of the conversation in the Issue before assignment @t-bello7 - please add a comment in the Issue #36 😁
