### ISSUE TITLE
[DOC] Add "Naming Convention" requirement to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Akshu-on-github** [AkshayaKulasekaran/Basic-Programs-Python#31]
## Summary
Add a requirement to follow these points for the names of the program files, commits and pull requests

### For Program Files
- Use the `.py` extension
- Use lowercase
- Use hyphens to separate words
- Example:
  ```md
  name-of-code-sample.py
  ```

### For commits
- Same as above
- Use [CODE] prefix for the first commit. Example:
  ```md
  [CODE] Add name-of-code-sample.py
  ```
- For other changes, use an imperative that describes the commit. Example:
  ```md
  Add comments for clarity
  ```

### For Pull Requests
- Use the first commit's message. Example:
  ```md
  [CODE] Add name-of-code-sample.py
  ```

**Comment by safalkora** [comment]
Interested!

**Comment by Akshu-on-github** [comment]
Thanks for taking this issue up @safalkora!

**Comment by Akshu-on-github** [comment]
Hey there @safalkora - may I know the current status of your issue?

**Comment by Akshu-on-github** [comment]
@safalkora, please let me know the status of this issue? If I don't receive a response within 2 days or so, I'll take it up myself
