### ISSUE TITLE
[DOC] Update the list in `./Programs/README.md`

### ISSUE THREAD

**Issue by Akshu-on-github** [AkshayaKulasekaran/Basic-Programs-Python#32]
## Summary
Update the list of programs in [./Programs/README.md](https://github.com/Akshu-on-github/Basic-Programs-Python/blob/master/Programs/README.md)
### Points to note:
Replace 
```md
- A simple calculator using Python3
- A simple ... using Python3
```
with
```md
- Calculator
- ...
```

**Comment by GopinathBalaji** [comment]
Hey! I would like to work on Updating the list in Programs/README.md

**Comment by Akshu-on-github** [comment]
Awesome, thanks for contributing to the project @GopinathBalaji!

**Comment by msaini26** [comment]
Hey, if possible @Akshu-on-github, I would also like to help with updating the list in Programs/README.md. I submitted my changes for review.

**Comment by Akshu-on-github** [comment]
Hey there @msaini26! Since this is a first come first serve assignment, @GopinathBalaji has the priority.

If @GopinathBalaji doesn't mind letting you have this issue, or goes over a week without response, I'll assign it to you and merge the PR

**Comment by GopinathBalaji** [comment]
I'm still interested on working on the issue

**Comment by msaini26** [comment]
No problem. This is my first time with open source, so I wasn't sure how it worked. 👍

**Comment by Akshu-on-github** [comment]
@msaini26 - ah, first-time contributions do tend to be a bit tricky! And I do believe that our CONTRIBUTING.md needs some work on that front, could you raise an issue for it? You'll get a green square!

**Comment by msaini26** [comment]
@Akshu-on-github That sounds good! I'll try it out. I opened a new issue. Is there something specific that you would like me to change within the document?
