### ISSUE TITLE
[DOC] Move Program Files to the `./Programs` folder

### ISSUE THREAD

**Issue by Akshu-on-github** [AkshayaKulasekaran/Basic-Programs-Python#33]
## Summary
Move the program files (those with extension `.py`) into the `./Programs` folder for improved organisation - remember to leave the following as is:
- README.md
- Code of Conduct
- License
- CONTRIBUTING.md
- `./.github`

**Comment by tanvi355** [comment]
I would like to do this.

**Comment by Akshu-on-github** [comment]
Thanks for taking up this issue @tanvi355!

**Comment by tanvi355** [comment]
There are 2 README files. Should I leave the Python programs list README as well?
