### ISSUE TITLE
[DOC] Rename Program Files to fit Naming Convention

### ISSUE THREAD

**Issue by Akshu-on-github** [AkshayaKulasekaran/Basic-Programs-Python#36]
## Summary
Rename the python program files as per the naming convention. Please refer to the naming convention in #31

**Comment by djs-djs** [comment]
Interested!

**Comment by donsmithsf** [comment]
I'm interested!

**Comment by t-bello7** [comment]
Okay I'm interested

**Comment by Akshu-on-github** [comment]
Hey there @djs-djs! Since @t-bello7 showed their interest in the main issue #30, priority goes to them. However, there are two other good first issues up for grabs in the aforementioned issue - please feel free to check them out!
