### ISSUE TITLE
Improve Contributing Guidelines

### ISSUE THREAD

**Issue by msaini26** [AkshayaKulasekaran/Basic-Programs-Python#40]
Updates needed on the CONTRIBUTING.md document.

**Comment by msaini26** [comment]
@Akshu-on-github Is there something specific you would like me to update?

**Comment by Akshu-on-github** [comment]
Not for now @msaini26 - needed a reminder on what people found confusing! Coud you briefly describe what you found confusing and what might help another in your shoes?

**Comment by msaini26** [comment]
@Akshu-on-github If this repository is for first time users, it might be helpful to explain step-by-step how to start. For example, first fork the repo, then clone it, create your own branch, make changes, etc. We can include code snippets of what to write exactly in the terminal. Let me know what you think.

**Comment by Akshu-on-github** [comment]
Indeed, I see these in several first-timer repos... but personally, I don't think it comes under the `CONTRIBUTING.md`. Instead, could you create a file called `FIRST_CONTRIBUTIONS.md` with the same @msaini26?

**Comment by msaini26** [comment]
Yes, sounds good @Akshu-on-github. 👍

**Comment by Akshu-on-github** [comment]
I've assigned this issue to you, please let me know how it goes!

**Comment by msaini26** [comment]
It's going well, thank you! I will make a pull request when I finish. @Akshu-on-github

**Comment by msaini26** [comment]
@Akshu-on-github Just finished, so I made a pull request. Let me know if anything needs to be changed.
