### ISSUE TITLE
[CODE] Add csv-reader.py

### ISSUE THREAD

**Issue by j-hussain** [AkshayaKulasekaran/Basic-Programs-Python#47]
**Topic**: 
**CSV Database**

Prior to using it, ensure there is a subdirectory named "datastore" with the hosted CSV files. Amend the constants at the start of the file accordingly.

**Checklist**:

- [x] I have gone through the existing code samples - there are no duplicates
- [x] I have gone through the open PRs and Issues with the `sample code` label - there are no duplicates
- [x] I will create a PR to add the sample code
- [ ] I have created a PR that adds the sample code
- [ ] I have updated the index appropriately

**Comment by Akshu-on-github** [comment]
Sounds good, go for it!

**Comment by j-hussain** [comment]
I have no idea on what to do from here, I've got my code, uploaded it to my forked repo, what next?

**Comment by Akshu-on-github** [comment]
Create a pull request - check out the [GitHub docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) and you should be good to go! I'd be happy to help with any further trouble though

**Comment by j-hussain** [comment]
Thanks, checked out the docs and created a PR!

**Comment by Akshu-on-github** [comment]
Thanks for contributing @j-hussain - I'll be closing this issue now
<details><summary></summary>
Resolved in #48 
</details>
